### ISSUE TITLE
Set Memberlog

### ISSUE THREAD

**Issue by AntianythingOnYT** [Nightcore5555/welcome-and-bye#1]
how do i set it to be a channel that the user mentions instead of a specific channel in a specific server

**Comment by Shedhatch** [comment]
Hello,

Sorry for the late reply.

For now it's designed to be set on a single channel and not a personalized one. But I agree, it will be a great feature. I'm trying to rework my whole code on every of my reps but it might take a long time to achieve.

Once again sorry for the late reply.

Have a good day!
